import type { Model, MutableModels } from "@earendil-works/pi-ai"; import type { ThinkingLevel } from "@earendil-works/pi-agent-core";
import { createSession, type Session } from "../../core/session/index.js"; import { createRuntime, type Runtime } from "../../core/runtime/index.js"; import type { SessionSnapshot } from "../../core/types.js";
import { createModelCollection, DEFAULT_MODEL_IDS, registerCustomModel, resolveCustomModelConfig, resolveProviderId, type CustomModelConfig } from "../../models/index.js"; import type { LlmTelemetrySink } from "../../telemetry.js";
import { buildCodeMentorPrompt } from "./agent-design/base-prompt.js"; import { getDefaultCodeProfiles } from "./agent-design/profiles.js"; import { createCodeRouterConfig } from "./router-config.js"; import { createCodeMentorState, type CodeMentorState } from "./state.js"; import { createCodeSnapshotExtension } from "./snapshot-extension.js"; import { createCodeToolManifest } from "./tools/manifest.js"; import { VirtualFS } from "./vfs.js"; import { createHttpExecClient, type ExecClient } from "./exec-client.js"; import type { CodeEvaluator } from "./evaluator.js"; import type { ProfileDefinition } from "../../core/types.js";
export interface CodeMentorConfig { models?: MutableModels; model?: Model<string>; customModel?: CustomModelConfig; providerId?: string; modelId?: string; thinkingLevel?: ThinkingLevel; systemPrompt?: string; profiles?: ProfileDefinition[]; vfs?: VirtualFS; exec?: ExecClient; evaluator?: CodeEvaluator; snapshot?: SessionSnapshot; maxTurns?: number; fetch?: typeof globalThis.fetch; llmTelemetry?: LlmTelemetrySink }
function resolve(config: CodeMentorConfig) { const profiles = config.profiles ?? getDefaultCodeProfiles(); const vfs = config.vfs ?? new VirtualFS(); const exec = config.exec ?? createHttpExecClient(); const codeState = createCodeMentorState(); const manifest = createCodeToolManifest(vfs, exec, config.evaluator); const router = createCodeRouterConfig(profiles, codeState); const extension = createCodeSnapshotExtension(codeState, vfs, profiles.map((p) => p.key)); const custom = config.customModel ?? resolveCustomModelConfig(); const models = config.models ?? createModelCollection(); const customProvider = custom ? registerCustomModel(models, custom) : undefined; const providerId = customProvider ?? config.providerId ?? resolveProviderId(); const modelId = custom?.id ?? config.modelId ?? process.env.MODEL_ID ?? DEFAULT_MODEL_IDS[providerId]; const model = config.model ?? models.getModel(providerId, modelId); if (!model) throw new Error(`找不到模型 ${providerId}/${modelId}`); return { profiles, vfs, codeState, models, model, domain: { id: "code", basePrompt: config.systemPrompt ?? buildCodeMentorPrompt(profiles, manifest), router, toolManifest: manifest, snapshotExtension: extension } }; }
export interface CodeMentor { runtime: Runtime; vfs: VirtualFS; state: CodeMentorState; profiles: ProfileDefinition[]; model: Model<string> }
export function createCodeMentor(config: CodeMentorConfig = {}): CodeMentor { const built = resolve(config); const runtime = createRuntime({ ...config, model: built.model, models: built.models, domain: built.domain }); return { runtime, vfs: built.vfs, state: built.codeState, profiles: built.profiles, model: built.model }; }
export interface CodeMentorSession extends Session { listFiles(): string[]; readFile(path: string): string | undefined; readonly modelInfo: string; readonly codeState: CodeMentorState }
export function createCodeMentorSession(config: CodeMentorConfig = {}): CodeMentorSession { const built = resolve(config); const session = createSession({ ...config, model: built.model, models: built.models, domain: built.domain, snapshot: config.snapshot }); return Object.assign(session, { listFiles: () => built.vfs.list(), readFile: (path: string) => { try { return built.vfs.read(path); } catch { return undefined; } }, modelInfo: `${built.model.provider}/${built.model.id}`, codeState: built.codeState }); }
